name: "Familier with actions"

on: push

jobs:
  run-a-simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Ashik'
      
      - name: output
        run: echo "${{steps.greet.outputs.time}}"

      - name: list files
        run: ls -a

      - name: checkout repo
        uses: actions/checkout@v1

      - name: list files
        run: ls -a

      - name: env variables
        run: |
          echo "COMMIT ID : ${{github.sha}}"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
        
